apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-devops-webapp
  template:
    metadata:
      labels:
        app: flask-devops-webapp
    spec:
      containers:
        - name: flask-webapp-container
          image: dzidulak/webapp-devops-project:latest
          ports:
          - containerPort: 5000 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-devops-webapp
  ports:
    - protocol: TCP
      port: 80 # Port for internal communication within the cluster
      targetPort: 5000 # Port exposed by your container
  type: ClusterIP